Fix Typescript errors
Fixes Typescript errors in SubscriptionDetails.tsx and Profile.tsx components.
- Fixes error TS2339: Property 'features' does not exist on type
- Fixes error TS2345: Argument of type 'number' is not assignable to parameter of type 'string'.
- Fixes error TS2322: Type '{ subscription: Subscription; invoices: any[]; }' is not assignable to type 'IntrinsicAttributes'.